# config file version
apiVersion: 1

# List of templates to import or update
templates:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the template, must be unique
    name: Simple
    # <string, required> content of the template
    template: |
      {{ define "Simple" }}
       {{.CommonAnnotations.Values}}
      {{ end }}