{
 "title": "Sensors",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wind",
   "type": "histogram",
   "description": "Wind",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mqtt2prometheus_wind", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Humidity",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mqtt2prometheus_humidity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt2prometheus_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature History",
   "type": "timeseries",
   "description": "Temperature History",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "mqtt2prometheus_temperature", "legendFormat": "__auto" }
   ]
  }
 ]
}